import { Message, ServiceListing } from "@/lib/types";

export const serviceListings: ServiceListing[] = [
  {
    id: "alex-fades",
    providerName: "Alex R.",
    serviceTitle: "West Campus Fade Lab",
    category: "Haircuts",
    price: 22,
    neighborhood: "West Campus",
    availability: ["Tonight", "This Week", "Weekends"],
    responseTime: "Usually replies in 8 min",
    bio: "Finance junior who has been cutting student fades and tapers since freshman year.",
    description:
      "Affordable fades, trims, and lineups for UT students. Best for clean evening cuts before org events or game-day weekends.",
    tags: ["fades", "lineup", "game day", "evenings"],
    trustScore: 93,
    rating: 4.9,
    reviewCount: 41,
    completedJobs: 118,
    vibe: "Polished",
    recentMomentum: "Booked 7 students this week",
    schedule: ["Tonight 7:00 PM", "Tonight 8:15 PM", "Tomorrow 6:30 PM"],
    reviews: [
      { author: "Jalen", rating: 5, quote: "Quick, clean fade before formal. Super easy pickup in West Campus." },
      { author: "Marco", rating: 5, quote: "Best campus haircut under 25 bucks." },
      { author: "Ethan", rating: 4.8, quote: "Consistent and actually on time." },
    ],
  },
  {
    id: "maya-braids",
    providerName: "Maya T.",
    serviceTitle: "Formal-Ready Braids",
    category: "Braiding",
    price: 35,
    neighborhood: "North Campus",
    availability: ["Tomorrow", "This Week", "Weekends"],
    responseTime: "Usually replies in 14 min",
    bio: "Studio art senior known around campus for event braids and natural hair styling.",
    description:
      "Protective styles, braid touch-ups, and event-ready looks with a calm, low-stress appointment flow.",
    tags: ["braids", "formal", "protective styles", "events"],
    trustScore: 95,
    rating: 5,
    reviewCount: 29,
    completedJobs: 72,
    vibe: "Premium",
    recentMomentum: "Most saved stylist before spring formals",
    schedule: ["Tomorrow 5:30 PM", "Thursday 4:00 PM", "Saturday 1:00 PM"],
    reviews: [
      { author: "Kyla", rating: 5, quote: "Maya literally saved my formal look." },
      { author: "Amara", rating: 5, quote: "Warm, detailed, and super professional." },
      { author: "Sydney", rating: 4.9, quote: "Worth it if you want a polished style that lasts." },
    ],
  },
  {
    id: "rishi-calc",
    providerName: "Rishi P.",
    serviceTitle: "Calc and Physics Rescue Sessions",
    category: "Tutoring",
    price: 28,
    neighborhood: "Guadalupe",
    availability: ["Tonight", "Tomorrow", "This Week"],
    responseTime: "Usually replies in 5 min",
    bio: "ECE senior with a reputation for getting people unstuck before exams.",
    description:
      "Fast-paced tutoring for calc, physics, and intro engineering classes. Good for last-minute concept rescue or exam prep.",
    tags: ["calc", "physics", "exam prep", "PCL"],
    trustScore: 90,
    rating: 4.8,
    reviewCount: 57,
    completedJobs: 140,
    vibe: "Casual",
    recentMomentum: "Heavy exam-week demand",
    schedule: ["Tonight 9:00 PM", "Tomorrow 1:00 PM", "Friday 3:00 PM"],
    reviews: [
      { author: "Naomi", rating: 5, quote: "Explains things like an older student, not a professor." },
      { author: "Derek", rating: 4.8, quote: "Saved me before my midterm." },
      { author: "Aisha", rating: 4.7, quote: "Really good if you need someone close to campus fast." },
    ],
  },
  {
    id: "lucia-headshots",
    providerName: "Lucia M.",
    serviceTitle: "Org Headshots and Grad Photos",
    category: "Photography",
    price: 45,
    neighborhood: "Downtown Austin",
    availability: ["This Week", "Weekends", "Flexible"],
    responseTime: "Usually replies in 20 min",
    bio: "Advertising major with a warm editorial style and a lot of org-client repeat business.",
    description:
      "Portraits, org headshots, graduation shots, and creator photos with soft editing and quick turnaround.",
    tags: ["headshots", "grad", "portraits", "org photos"],
    trustScore: 88,
    rating: 4.9,
    reviewCount: 25,
    completedJobs: 61,
    vibe: "Premium",
    recentMomentum: "Popular with org exec boards",
    schedule: ["Friday 5:00 PM", "Saturday 10:00 AM", "Sunday 2:30 PM"],
    reviews: [
      { author: "Bella", rating: 5, quote: "My LinkedIn finally looks like I have my life together." },
      { author: "Chris", rating: 4.9, quote: "Great communication and fast edits." },
      { author: "Aarav", rating: 4.8, quote: "Worth the extra spend if you want polished photos." },
    ],
  },
  {
    id: "zoe-resume",
    providerName: "Zoe C.",
    serviceTitle: "Resume Rescue for Intern Season",
    category: "Resume Review",
    price: 18,
    neighborhood: "West Campus",
    availability: ["Tonight", "Tomorrow", "Flexible"],
    responseTime: "Usually replies in 3 min",
    bio: "McCombs senior who has helped dozens of students tighten resumes before recruiting.",
    description:
      "Sharp edits, bullet rewrites, and quick feedback for internship and org applications.",
    tags: ["resume", "internships", "McCombs", "quick turnaround"],
    trustScore: 91,
    rating: 4.9,
    reviewCount: 38,
    completedJobs: 110,
    vibe: "Polished",
    recentMomentum: "Popular during recruiting deadlines",
    schedule: ["Tonight 8:30 PM", "Tomorrow 11:00 AM", "Tomorrow 7:00 PM"],
    reviews: [
      { author: "Priya", rating: 5, quote: "Got way more interviews after Zoe cleaned up my resume." },
      { author: "Luis", rating: 4.8, quote: "Fastest turnaround I found near campus." },
      { author: "Mei", rating: 5, quote: "Actually useful feedback, not vague fluff." },
    ],
  },
  {
    id: "trent-moveout",
    providerName: "Trent W.",
    serviceTitle: "West Campus Move-Out Muscle",
    category: "Moving Help",
    price: 30,
    neighborhood: "West Campus",
    availability: ["This Week", "Weekends", "Flexible"],
    responseTime: "Usually replies in 11 min",
    bio: "Kinesiology junior with a truck and a flexible weekend schedule.",
    description:
      "Move-out lifting help, furniture pickup, and apartment-to-storage runs around West Campus and North Campus.",
    tags: ["moving", "truck", "storage", "move-out"],
    trustScore: 87,
    rating: 4.7,
    reviewCount: 21,
    completedJobs: 54,
    vibe: "Casual",
    recentMomentum: "Most booked during lease turnover",
    schedule: ["Thursday 6:00 PM", "Saturday 9:00 AM", "Sunday 12:00 PM"],
    reviews: [
      { author: "Nina", rating: 4.8, quote: "Made move-out so much less awful." },
      { author: "Sam", rating: 4.7, quote: "Good value if you just need someone reliable." },
      { author: "Eli", rating: 4.6, quote: "Communicative and easy to coordinate with." },
    ],
  },
];

export const starterThreads: Record<string, Message[]> = {
  "alex-fades": [
    {
      id: "seed-1",
      listingId: "alex-fades",
      sender: "seller",
      body: "Hey! I’ve got 7:00 and 8:15 open tonight if you want either spot.",
      timestamp: "6:08 PM",
    },
  ],
  "maya-braids": [
    {
      id: "seed-2",
      listingId: "maya-braids",
      sender: "seller",
      body: "Happy to help. Tell me the style you’re aiming for and I can suggest the best slot.",
      timestamp: "4:42 PM",
    },
  ],
};
